package com.mlongbo.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResourceslog<M extends BaseResourceslog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setOsname(java.lang.String osname) {
		set("osname", osname);
		return (M)this;
	}

	public java.lang.String getOsname() {
		return get("osname");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setHostname(java.lang.String hostname) {
		set("hostname", hostname);
		return (M)this;
	}

	public java.lang.String getHostname() {
		return get("hostname");
	}

	public M setCpunumber(java.lang.Long cpunumber) {
		set("cpunumber", cpunumber);
		return (M)this;
	}

	public java.lang.Long getCpunumber() {
		return get("cpunumber");
	}

	public M setCpuratio(java.math.BigDecimal cpuratio) {
		set("cpuratio", cpuratio);
		return (M)this;
	}

	public java.math.BigDecimal getCpuratio() {
		return get("cpuratio");
	}

	public M setPhymemory(java.lang.Long phymemory) {
		set("phymemory", phymemory);
		return (M)this;
	}

	public java.lang.Long getPhymemory() {
		return get("phymemory");
	}

	public M setPhyfreememory(java.lang.Long phyfreememory) {
		set("phyfreememory", phyfreememory);
		return (M)this;
	}

	public java.lang.Long getPhyfreememory() {
		return get("phyfreememory");
	}

	public M setDiskmemory(java.lang.Long diskmemory) {
		set("diskmemory", diskmemory);
		return (M)this;
	}

	public java.lang.Long getDiskmemory() {
		return get("diskmemory");
	}

	public M setDiskfreememory(java.lang.Long diskfreememory) {
		set("diskfreememory", diskfreememory);
		return (M)this;
	}

	public java.lang.Long getDiskfreememory() {
		return get("diskfreememory");
	}

	public M setJvmtotalmemory(java.lang.Long jvmtotalmemory) {
		set("jvmtotalmemory", jvmtotalmemory);
		return (M)this;
	}

	public java.lang.Long getJvmtotalmemory() {
		return get("jvmtotalmemory");
	}

	public M setJvmfreememory(java.lang.Long jvmfreememory) {
		set("jvmfreememory", jvmfreememory);
		return (M)this;
	}

	public java.lang.Long getJvmfreememory() {
		return get("jvmfreememory");
	}

	public M setJvmmaxmemory(java.lang.Long jvmmaxmemory) {
		set("jvmmaxmemory", jvmmaxmemory);
		return (M)this;
	}

	public java.lang.Long getJvmmaxmemory() {
		return get("jvmmaxmemory");
	}

	public M setGccount(java.lang.Long gccount) {
		set("gccount", gccount);
		return (M)this;
	}

	public java.lang.Long getGccount() {
		return get("gccount");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
