package com.mlongbo.jfinal.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("advice", "id", Advice.class);
		arp.addMapping("beauty", "id", Beauty.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("blogcategory", "id", Blogcategory.class);
		arp.addMapping("gonggao", "id", Gonggao.class);
		arp.addMapping("iplog", "id", Iplog.class);
		arp.addMapping("link", "id", Link.class);
		arp.addMapping("picrecommend", "id", Picrecommend.class);
		arp.addMapping("qquser", "id", Qquser.class);
		arp.addMapping("resourceslog", "id", Resourceslog.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("userlogininfo", "id", Userlogininfo.class);
		arp.addMapping("userrole", "id", Userrole.class);
		arp.addMapping("video", "id", Video.class);
	}
}

