package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseAdvice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advice extends BaseAdvice<Advice> {
	public static final Advice dao = new Advice().dao();
}
