package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseBeauty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Beauty extends BaseBeauty<Beauty> {
	public static final Beauty dao = new Beauty().dao();
}
