package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseBlogcategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blogcategory extends BaseBlogcategory<Blogcategory> {
	public static final Blogcategory dao = new Blogcategory().dao();
}
