package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseGonggao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gonggao extends BaseGonggao<Gonggao> {
	public static final Gonggao dao = new Gonggao().dao();
}
