package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseIplog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Iplog extends BaseIplog<Iplog> {
	public static final Iplog dao = new Iplog().dao();
}
