package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Link extends BaseLink<Link> {
	public static final Link dao = new Link().dao();
}
