package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BasePicrecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picrecommend extends BasePicrecommend<Picrecommend> {
	public static final Picrecommend dao = new Picrecommend().dao();
}
