package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseQquser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Qquser extends BaseQquser<Qquser> {
	public static final Qquser dao = new Qquser().dao();
}
