package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseResourceslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resourceslog extends BaseResourceslog<Resourceslog> {
	public static final Resourceslog dao = new Resourceslog().dao();
}
