package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseUserlogininfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userlogininfo extends BaseUserlogininfo<Userlogininfo> {
	public static final Userlogininfo dao = new Userlogininfo().dao();
}
