package com.mlongbo.jfinal.model;

import com.mlongbo.jfinal.model.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {
	public static final Video dao = new Video().dao();
}
